#There is the configuration for state and transitions analysis


#All generated files will be saved here. Last name in this path is the name that will be assignet to all generated files
output_files: EXAMPLE\test

#Table and sheet where data to analysis will be take from
input_directory: tables_to_analisys
input_table: EXAMPLE.xlsx
input_sheet: test

#States and transitions will be assigned to object based on these table columns.
#When values from objects columns is same for several states/transitions then these states/transitions will be related to this object
#You may mention here a several columns. So each unique compination of values of mentioned columns will be considered as one unique object
objects:
   - TestCase

#Sequence of transitions and states will be considered based on this field
sequences:
   - StepID
   
#Transitions will be took from these fields
#You may mention here a several columns. Each unique combination of values of mentioned columns will be considered as one transition
transitions:
   - Action

#States will be took from these fields
#You may mention here a several columns. Each unique combination of values from mentioned columns will be considered as one state
states:
   - CountToPlace
   - CountToCancel

